### ISSUE TITLE
assertion signature different for webauthn client compared to fido2-assert program

### ISSUE THREAD

**Issue by sb230132** [Yubico/libfido2#461] opened 2021-11-11 07:10 UTC
Hi,
I have done U2F registration of a token device against a user on RP server.
Now when i authenticate using fido2-assert program assertion passes.
However same user when i try to connect to RP server from webauthn client i get assertion failure.

What i notice is the assertion signature received from both the clients is different:

Signature received as part of fido2-assert client is:
fido_check_flags: flags=01
fido_check_flags: up=0, uv=0
fido_verify_sig_es256: sig->len=71
fido_verify_sig_es256: sig->ptr=0x12bf8dd30
0000: 30 45 02 20 0d ff 26 46 74 75 fb b1 2b f3 a3 d4
0016: 63 c9 98 d7 c6 b9 b0 8b b2 e0 d4 56 e9 25 6f 08
0032: 87 35 cf 62 02 21 00 f7 e3 26 ea 67 12 42 33 43
0048: a6 28 93 0c ec 16 15 8b 8c 27 d0 23 ef 1f 94 28
0064: e3 51 4d 3d 40 62 a7

Signature received as part of webauthn client is:
fido_check_flags: flags=01
fido_check_flags: up=0, uv=0
fido_verify_sig_es256: sig->len=71
fido_verify_sig_es256: sig->ptr=0x12bf8e960
0000: 30 45 02 20 13 a6 2f 20 a1 b3 93 ab cb 19 bf 68
0016: ea 09 01 b5 9d 16 7b 51 6d d9 79 da 99 1e d2 14
0032: 2f 21 0c 31 02 21 00 a8 32 4e c3 52 b9 70 b6 ee
0048: a1 c6 12 2e 76 6d 8a 4e 23 75 70 16 83 7a 6e 98
0064: 34 ab 5c b3 1b d8 be
fido_verify_sig_es256: ECDSA_verify

Why is the signature different for the same user ? Is this expected ? Or iam missing something here ?

Regards
Satish.B

**Comment by martelletto** [comment] 2021-11-11 08:05
There are a few extra hoops involved when it comes to interoperability between FIDO2 and webauthn. In particular, double-check that `authdata` is encoded correctly, and that `clientdata` matches the format followed by webauthn. A complete webauthn client using libfido2 can be found at https://github.com/martelletto/fido2-webauthn-client.

**Comment by sb230132** [comment] 2021-11-11 10:16
I checked authenticatorData which is same in both cases, except the last byte (which is increasing for each authentication). Seems like a counter.

However clientdata is set via call to fido_assert_set_clientdata_hash().
In webauthn client clientdata is first converted to SHA256 and then fido_assert_set_clientdata_hash() is called.

Does this cause any trouble ?

**Comment by martelletto** [comment] 2021-11-11 10:22
What is the data that is being hashed? Please make sure it follows this format: https://github.com/martelletto/fido2-webauthn-client/blob/master/clientdata.c#L32-L37. The exact payload depends on the RP.

**Comment by sb230132** [comment] 2021-11-16 11:06
Below is the challenge (during registration/authentication) which i HASH it and set in fido_assert_set_clientdata_hash().

Server registration: Clientdata: {"type":"webauthn.create","challenge":"~??
m?]<?Z?e?l)Ig?????1?r?\k","origin":"http://localhost:8080","crossOrigin":false}

Server authentication: Clientdata: {"type":"webauthn.get","challenge":"?h?Z????P??>CԞ??%E?Թ??Ϝ","origin":"http://localhost:8080","crossOrigin":false}


I perform registration step as part of standalone client/server C++ based application.
Iam able to do authentication with same application.
When i try to authenticate from browser, assertion step fails.

Not sure what is wrong in case of browser based authentication.

**Comment by martelletto** [comment] 2021-11-17 09:06
That challenge looks a bit strange. Please take a closer look at https://github.com/martelletto/fido2-webauthn-client; in particular, https://github.com/martelletto/fido2-webauthn-client/blob/master/README#L541-L546 and clientdata_json(). Note that the challenge is base64-encoded, and that the whole JSON blob is hashed and passed to fido_assert_set_clientdata_hash(): https://github.com/martelletto/fido2-webauthn-client/blob/master/webauthn-assert.c#L147-L157.

**Comment by sb230132** [comment] 2021-11-24 06:25
Ok.

Below even though we decode challenge we still set base64 encoded challenge in client data.
Whats the point of calling base64_decode(), its of no use. I dont see ptr being used anywhere later.

https://github.com/martelletto/fido2-webauthn-client/blob/1504a90a5c70ac42adbe0d515e896d474a2e21f1/clientdata.c

	if (base64_decode(challenge, &ptr, &len) < 0 || len < 32) {
		warnx("%s: challenge", __func__);
		goto fail;
	}

	if ((n = snprintf(buf, sizeof(buf), "{\"type\":\"%s\",\"challenge\":"
	    "\"%s\",\"origin\":\"%s\",\"crossOrigin\":false}", type, challenge,
	    ORIGIN)) < 0 || (size_t)n >= sizeof(buf)) {
		warnx("%s: snprintf", __func__);
		goto fail;
	}

**Comment by martelletto** [comment] 2021-11-24 07:09
The check:

```c
if (base64_decode(challenge, &ptr, &len) < 0 || len < 32)
```

asserts that `challenge` is a base64-encoded string, and that the length of the decoded blob is at least 32 bytes.

**Comment by sb230132** [comment] 2021-11-24 07:22
Ok, thanks.

**Comment by ruiquelhas** [comment] 2021-11-24 16:38
@martelletto besides `clientdata` and `authdata`, as you mentioned, is there anything else we need to have into account to ensure interoperability with WebAuthn? In this case, as mentioned by @sb230132 to ensure the signatures match when the device is registered with `libfido2`, but the authentication can occur using a different client implementation.

For instance, considering a WebAuhn client implementation like a web browser, which (if following the W3C standard) provides a `navigator.credentials.get()` API to obtain the assertion. 

This particular API will eventually yield a JavaScript `ArrayBuffer` for both the `authdata` and `signature` parameters. The corresponding byte strings are not CBOR-encoded, as far as I was able to understand, which means that, in the case of `authdata`, we need to manually encode it before using [`fido_assert_set_authdata()`](https://developers.yubico.com/libfido2/Manuals/fido_assert_set_authdata.html). I'm assuming there's nothing we should do about the `signature` parameter, and the corresponding byte string can be used directly with [`fido_assert_set_sig()`](https://developers.yubico.com/libfido2/Manuals/fido_assert_set_sig.html). Is that correct?

For the registration, we create a SHA256 hash of a JSON string with the following format:

```json
{
  "type": "webauthn.create",
  "challenge": "<registration_base64_challenge_string>",
  "origin": "https://example.com:80"
  "crossOrigin": false
}
```

and use it on [`fido_cred_set_clientdata_hash`](https://developers.yubico.com/libfido2/Manuals/fido_cred_set_clientdata_hash.html). And then for the authentication, we create a SHA256 hash of a JSON string with the following format:

```json
{
  "type": "webauthn.get",
  "challenge": "<authentication_base64_challenge_string>",
  "origin": "https://example.com:80"
  "crossOrigin": false
}
```

However, the signature verification still fails, which leads me to believe there is still something missing. Either my assumptions about the assertion data returned by the WebAuthn client implementation are wrong (I don't think so) or there's some kind of incompatibility created during registration. It might also be an issue with the relying party implementation, but everything works fine with a `libfido2`-based client, so again we are still missing some piece of the puzzle for `WebAuthn`.

By the way, this happens with `libfido2` 1.5.0, which begs the question, was there any WebAuthn incompatibility fixed in the meantime (up until 1.9.0)?

Thanks

**Comment by martelletto** [comment] 2021-11-24 17:56
I am sick and OOH. Please bear with me. First, to answer your question: I am not aware of any WebAuthn-related incompatibility fixed since 1.5.0. Some questions and observations:

- Does signature verification fail for both registration and authentication?
- Please note that's not a valid JSON payload (no comma after `origin`);
- Please note the order of the fields in the JSON payload (in contrast with https://github.com/martelletto/fido2-webauthn-client/blob/master/README#L541-L546);
- Have you tried dropping the port denominator (`:80`) from the origin?

Thank you,

-p.

**Comment by ruiquelhas** [comment] 2021-11-24 20:20
> I am sick and OOH. Please bear with me. 

No worries. That's not good. I wish you a speedy recovery!

> Does signature verification fail for both registration and authentication?

Only authentication via browser WebAuthn fails. Registration is done using a libfido2 client.

> Please note that's not a valid JSON payload (no comma after origin);

Right, that was an unintentional copy paste issue.

> Please note the order of the fields in the JSON payload (in contrast with https://github.com/martelletto/fido2-webauthn-client/blob/master/README#L541-L546);

Does it matter? I guess because of the hash. I believe it's the same but I'll double check.

> Have you tried dropping the port denominator (:80) from the origin?

No, but given that it's hashed, I would assume it's not a problem but I'll double check as well.

Thanks!

**Comment by martelletto** [comment] 2021-11-25 08:17
The order of the fields is probably a red herring; my bad. Is there a way to retrieve the `clientDataJSON` used by the client?

**Comment by ruiquelhas** [comment] 2021-11-25 10:29
Yes, and I think I might have figured out the issue. The problem is that the WebAuthn `clientDataJSON` used by the authenticator relies on URL-safe `base64` encoding for the `challenge` parameter, whereas our server implementation does not. This means the SHA256 output will be different, so that's probably the issue.

So, in our case, the client yields:

```json
{
  "type": "webauthn.get",
  "challenge": "Z_IOQ8v97UDtyZU7TRvlqb7HF2j30YUfyX1L5Jfo1KI",
  "origin": "https://baderous.xyz",
  "crossOrigin": false
}
```

And the server, for verifying the assertion,  sets (`fido_assert_set_clientdata_hash()`) a SHA256 hash of:

```json
{
  "type": "webauthn.get",
  "challenge": "Z/IOQ8v97UDtyZU7TRvlqb7HF2j30YUfyX1L5Jfo1KI=",
  "origin": "https://baderous.xyz",
  "crossOrigin": false
}
```

**Comment by ruiquelhas** [comment] 2021-11-29 18:53
The remaining incompatibility was indeed caused by the fact that the client was using a URL-safe base64 `challenge` parameter whereas the server was not.

Thanks for the help @martelletto. Feel free to close the issue.

**Comment by martelletto** [comment] 2021-11-30 07:28
Glad to hear the issue was identified!

**Closed by martelletto** 2021-11-30 07:28 UTC
Labels: question
