### ISSUE TITLE
Compilation with visual studio 2019

### ISSUE THREAD

**Issue by janhec** [Yubico/libfido2#106] opened 2019-12-29 14:12 UTC
1) The shared libraries fail to link when a (usual) path to repos with spaces is used. The path after /def: should be quoted. Line 324-325 become:
	`string(CONCAT CMAKE_SHARED_LINKER_FLAGS ${CMAKE_SHARED_LINKER_FLAGS} " /def:\"${CMAKE_CURRENT_SOURCE_DIR}/src/export.msvc\"")`
(can't get the 'code' to display correctly. The " after LINKER_FLAGS} should be followed by a space and then only the /def:...).
2) In the powershel script, `Invoke-WebRequest ${LIBRESSL_URL}/${LIBRESSL}.tar.gz` fails, probably because default TLS is lower than required TLS12 of https://ftp.openbsd.org/ (checked with https://www.ssllabs.com/ssltest/analyze.html). However, I could not resolve this and had to download libressl-3.0.2.tar.gz(.asc) by hand.
EDIT: My bad. I overlooked line 10 in the script (and added similar ;( ). 
Clearly my diag is wrong. Hope to find out more, but it is not a priority, esp. if nobody else has this.
Lastly: in case of repeated run of the powershell script, it would be nice to encapsulate the new directory making in something like `if (-not (Test-Path $BUILD)) {}`
Thanks, Jan

**Comment by martelletto** [comment] 2019-12-30 08:51
Hi,

> * The shared libraries fail to link when a (usual) path to repos with spaces is used. The path after /def: should be quoted. Line 324-325 become:
>   `string(CONCAT CMAKE_SHARED_LINKER_FLAGS ${CMAKE_SHARED_LINKER_FLAGS} " /def:\"${CMAKE_CURRENT_SOURCE_DIR}/src/export.msvc\"")`
>   (can't get the 'code' to display correctly. The " after LINKER_FLAGS} should be followed by a space and then only the /def:...).

Thanks. Fixed in 3634790.

> * In the powershel script, `Invoke-WebRequest ${LIBRESSL_URL}/${LIBRESSL}.tar.gz` fails, probably because default TLS is lower than required TLS12 of https://ftp.openbsd.org/ (checked with https://www.ssllabs.com/ssltest/analyze.html). However, I could not resolve this and had to download libressl-3.0.2.tar.gz(.asc) by hand.
>   Lastly: in case of repeated run of the powershell script, it would be nice to encapsulate the new directory making in something like `if (-not (Test-Path $BUILD)) {}`

I unfortunately don't have a Windows installation at hand to reproduce this issue. `build.ps1` should already be using TLS 1.2, or at least that is what my (somewhat limited) understanding of PowerShell tells me:

https://github.com/Yubico/libfido2/blob/36347900fd1bdc5c6bdc85fc730677788ace6034/windows/build.ps1#L10

The [GitHub Actions runner doing CI Windows builds](https://github.com/Yubico/libfido2/runs/367535374) (using `build.ps1`) seems to be happy, which is strange.

-p.

**Comment by martelletto** [comment] 2020-02-11 21:17
Closing as the problem affecting `Invoke-WebRequest` does not seem reproducible. Feel free to reopen if you have more information.

**Closed by martelletto** 2020-02-11 21:17 UTC
