### ISSUE TITLE
is_fido function

### ISSUE THREAD

**Issue by shimritd** [Yubico/libfido2#61] opened 2019-10-03 20:48 UTC
hi,

in the is_fido function we have:
return (usage_page == 0xf1d0);

well, it worked perfect but suddenly i get 1 as the device usage_page and therefor this condition returns false.
any idea what can be the reason?
i updated windows yesterday, this is the only reason i can think of...

thanks,
Shimrit

**Comment by martelletto** [comment] 2019-10-04 10:28
On 03/10/2019 22:48, shimritd wrote:
> hi,
> 
> in the is_fido function we have:
> return (usage_page == 0xf1d0);
> 
> well, it worked perfect but suddenly i get 1 as the device usage_page and therefor this condition returns false.
> any idea what can be the reason?
> i updated windows yesterday, this is the only reason i can think of...
> 
> thanks,
> Shimrit
> 
> 
> 

Hi Shimrit,

I am currently on vacation, and can take a closer look once I am back.
In the meantime: did you upgrade to Windows 1903? Do you observe a
difference in behaviour if you run the application in administrator mode?

-p.

**Comment by shimritd** [comment] 2019-10-05 05:18
Yes, it's 1903...

I'll try to check it running as admin.
Thanks

בתאריך 4 באוק׳ 2019 12:29,‏ pedro martelletto <notifications@github.com> כתב:
On 03/10/2019 22:48, shimritd wrote:
> hi,
>
> in the is_fido function we have:
> return (usage_page == 0xf1d0);
>
> well, it worked perfect but suddenly i get 1 as the device usage_page and therefor this condition returns false.
> any idea what can be the reason?
> i updated windows yesterday, this is the only reason i can think of...
>
> thanks,
> Shimrit
>
>
>

Hi Shimrit,

I am currently on vacation, and can take a closer look once I am back.
In the meantime: did you upgrade to Windows 1903? Do you observe a
difference in behaviour if you run the application in administrator mode?

-p.

**Comment by prusnak** [comment] 2019-10-22 15:43
@shimritd any news?

**Comment by shimritd** [comment] 2019-10-23 09:03
Hi,

This is what I got when I printed all devices in manifest (I commented the is_fido function):

\\?\hid#vid_1050&pid_0407&mi_01#7&157bc0b2&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}: vendor=0x1050, product=0x0407 (Yubico YubiKey OTP+FIDO+CCID)
\\?\hid#vid_1050&pid_0407&mi_00#7&28abdcf0&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\kbd: vendor=0x1050, product=0x0407 (Yubico YubiKey OTP+FIDO+CCID)

See the \kbd at the end of the path in the second line.
Why there are two lines if there is only one yubikey connected?


I re-install the hid device from device manager and now it is ok…

**Comment by shimritd** [comment] 2019-10-23 09:50
We have another problem with a customer that bought Yubikey with the new firmware (5.2.4).
They fail on fido_dev_is_fido2.
Could it be that the attr.flags of the device was changed?

We will buy Yubikeys with the same firmware to check it but can you say if you know that problem?

Shimrit

**Comment by martelletto** [comment] 2019-10-23 11:20
On 23/10/2019 11:50, shimritd wrote:
> We have another problem with a customer that bought Yubikey with the new firmware (5.2.4).
> They fail on fido_dev_is_fido2.
> Could it be that the attr.flags of the device was changed?
> 
> We will buy Yubikeys with the same firmware to check it but can you say if you know that problem?
> 
> Shimrit

Hi Shimrit,

We are not aware of any problem concerning 5.2.4 and
fido_dev_is_fido2(). I quickly tested it on a 5.2.4 device and it works
as expected. Could the customer have disabled FIDO2 using YubiKey Manager?

-p.

**Comment by shimritd** [comment] 2019-10-23 11:31
No, we had a remote session with them, and we asked them to open YubiKey Manager, FIDO2 was set.
And I still have problems with the is_fido() function, it cannot identify my key.
I tried to uninstall the device from device manager, it solved the problem but now it happened again. Any clue?

**Comment by shimritd** [comment] 2019-10-23 11:38
I forget to say that I cannot reset the key with the YubiKey Manager on my PC, I’m getting an error. The Yubikey can be reset on another PC.

**Comment by martelletto** [comment] 2019-10-23 13:55
Hi Shimrit,

This is what I observe on a Windows 1903 (build 19008.1) VM running libfido2 HEAD against a YubiKey 5.2.4:

- If I execute 'fido2-token -L' without administrator privileges, the application is unable to see the key, let alone communicate with it. This is a known problem in Windows 1903, as it restricts access to FIDO HID devices to applications using its native FIDO API or applications running in administrator mode (see issue #34);
- If I execute 'fido2-token L' with administrator privileges, the application sees one YubiKey;
- If I execute 'fido2-token -I <device path>' with administrator privileges, the application correctly identifies the YubiKey as a FIDO2 device. 

Regarding the issues described:

- Did you modify is_fido() or comment out its invocation? If so, it is possible the library is detecting the OTP interface (keyboard) as FIDO, which would explain the two devices listed for a single key (and the \kbd suffix on the second one);
- Could the failure to reset be caused by the 5-second rule (see issue #15)?

Thank you,

-p.

**Comment by shimritd** [comment] 2019-10-24 21:58
Thanks a lot!
We solved the problem. We updated Yubikey Manager and we run as admin and it works.

BUT, we bought the new keys with firmware 5.2.4 as our customer has.
It doesn’t work for us either…
Even if we execute only info.exe from libfido2-master lib, we get an error on parse_reply_element where we get into the default case…
Any reason you can think of?

Thanks!

**Comment by martelletto** [comment] 2019-10-25 10:25
Are you running with commit 325ef43f, from June 10? The described behaviour suggests otherwise.

-p.

**Comment by shimritd** [comment] 2019-10-29 11:26
We downloaded the latest version from https://github.com/Yubico/libfido2

I’m running your cred and assert examples, both pass with uv=false but fail with uv=true.
This is true only with the new firmware: 5.2.4.
I tried to set a pin both via the YubiKey Manager and also via setpin.exe, same behavior.

Can you please check?

Thanks,
Shimrit

**Comment by martelletto** [comment] 2019-10-30 14:50
Hi,

I was able to use fido2-cred.exe from https://developers.yubico.com/libfido2/Releases/libfido2-1.2.0-win64.zip to generate a credential on a key with firmware 5.2.4.

A third question: is your application calling fido_cred_set_options() and setting UV to true? If so, you may want to set UV to false, or use fido_assert_set_up() and fido_assert_set_uv() instead. I believe there is a difference in behaviour between 5.2.4 and previous versions that could be causing the problem you are observing.

-p.

**Comment by martelletto** [comment] 2019-10-30 16:29
Yes, that should also work. You will get FIDO_ERR_UNSUPPORTED_OPTION from examples/cred if you pass it -v on a YubiKey, as the YubiKey does not support UV as understood by FIDO2.

**Comment by martelletto** [comment] 2019-10-30 18:05
Hi,

UV means the device is "capable of verifying the user within itself"; ClientPIN means PIN code verification: https://fidoalliance.org/specs/fido-v2.0-ps-20190130/fido-client-to-authenticator-protocol-v2.0-ps-20190130.html#authenticatorGetInfo

How are you trying to use hmac-secret?

Regarding a phone call, please contact Yubico's support at https://www.yubico.com/support/contact/.

-p.

**Comment by shimritd** [comment] 2019-10-30 18:20
Ok, thank.
We simply set -h in cred.exe. It fails when ext!=0...


בתאריך 30 באוק׳ 2019 20:05,‏ pedro martelletto <notifications@github.com> כתב:

Hi,

UV means the device is "capable of verifying the user within itself"; ClientPIN means PIN code verification: https://fidoalliance.org/specs/fido-v2.0-ps-20190130/fido-client-to-authenticator-protocol-v2.0-ps-20190130.html#authenticatorGetInfo

How are you trying to use hmac-secret?

Regarding a phone call, please contact Yubico's support at https://www.yubico.com/support/contact/.

-p.

**Comment by shimritd** [comment] 2019-10-31 05:39
We register with ext=0, and authenticate with hmac-secret and it works, thanks!

**Comment by martelletto** [comment] 2019-10-31 12:25
Hi,

Great to hear! I will close this issue, then. If anything else pops up, let me know.

-p.

**Closed by martelletto** 2019-10-31 12:25 UTC
