### ISSUE TITLE
Windows: Abstraction layer for system's native API

### ISSUE THREAD

**Issue by prusnak** [Yubico/libfido2#153] opened 2020-04-08 08:32 UTC
From README:
> On Windows 1903 and newer versions, access to FIDO devices has been restricted to applications using the operating system's native API. Use of *libfido2* is still possible in privileged applications.

I think libfido2 should become a wrapper for the system’s native API (same as libhidapi which just wraps OS native API for HID on Windows instead of using libusb).

That way we can support both privileged and unprivileged applications.

**Comment by My1** [comment] 2020-04-08 09:03
Although question is what the windows api allows in fido stuff not that it goes and filters all sorts of stuff out, as that would make it quite weird on w10 when some things do and others don't work (like for example credential management or vendor stuff that would need to be tested.

**Comment by riedel** [comment] 2020-04-08 16:50
see  #34

**Comment by martelletto** [comment] 2020-04-10 08:38
As @riedel pointed out, this is effectively a duplicate of #34. Let's move the conversation there.

**Closed by martelletto** 2020-04-10 08:38 UTC
