### ISSUE TITLE
Reader Failes After Invalid Verification

### ISSUE THREAD

**Issue by shawnkk** [Yubico/libfido2#321] opened 2021-04-09 16:37 UTC
I have an Authentrend Atkey.pro. This works fine if a valid print is used but goes in to some kind of failure mode if anvalid fingerprint or timeout etc. is encountered. When this happens the reader can no longer be used until it is unplugged and then plugged back in again. This happens on the latest version of libfido2 (1.7.0) but was also happening on the previous libu2fhost/libu2fserver libraries. Is this a known problem and if so is there a work around? As it is, this makes the fingerprint reader pretty much useless since you never know when it's going to fail.

**Comment by martelletto** [comment] 2021-04-10 08:46
The problem isn't known (to me, at least). Would it be possible to capture the output of `FIDO_DEBUG=1`? Does the token behave differently with a different application, e.g. Google Chrome?

**Comment by shawnkk** [comment] 2021-04-12 17:40
I've attached the log of a successful authentication as well as the log for a failed authentication. Authentrend says the token is supported using linux. They even have instructions for getting it working with pamu2f. Unfortunately the machine being used with the token is a headless server so it's not possible to test with something like Chrome. Not that that would be very easy either.
If I might make a suggestion, I think a command line utility is needed for testing a token. Something simple that doesn't require a masters degree in cryptography to run to test the basic functionality of a token to make sure it works before going to all the trouble of setting it up for real use.
 [successful_authentication.txt](https://github.com/Yubico/libfido2/files/6298594/successful_authentication.txt)
[failed_authentication.txt](https://github.com/Yubico/libfido2/files/6298599/failed_authentication.txt)

**Comment by nuno0529** [comment] 2021-04-13 11:31
@shawnkk 
The ATKey will force to add the check of any configured fingerprint as User Verification when receiving getAssert command with up=true as alwaysUv behavior. The failed code of 0x36 in your log should be due to the fingerprint sensor is locked due to
- 3 times fingerprint verification failed in one power cycle
- totally 15 times fingerprint verification failed 
  ( timeout won't be considered as fingerprint verification failed in normal way to use.)
Then the ATKey can just return 0x36 as CTAP2_ERR_PUAT_REQUIRED to ask client tool to try PIN instead.

So in your case if you want to use with getAssert command with up=true and uv=false, I will suggest just delete the fingerprints  of the key and just use PIN to protect the credentials of the key should be enough.

Although client tool can just send command with up=false to not check User Presence and use this as result, but this may not what the client application likes pam-u2f want to behave.

**Comment by martelletto** [comment] 2021-04-13 11:39
Thank you for your contribution, @nuno0529. FWIW, I agree with the diagnosis. This sounds like something that will ultimately need to be handled by the application (pam-u2f in this case).

**Comment by shawnkk** [comment] 2021-04-13 17:54
This information about the Atkey is helpful. This does appear to be what's happening, the reader is going in to a pin required state after a failed attempt. Is there any way to get it out of this locked state? This seems like the kind of thing that should clear once a valid pin is entered.
In my application the user is only going to have access to the fingerprint reader and a push button to start the authentication process. The application itself can send the pin if some kind of reset is required.
I'm trying to get a process as simple as possible: the user pushes the button, then touches the fingerprint sensor. If the print is known then authorize and if not then don't. Having them enter pin codes or power cycle parts of the hardware just isn't an option.
In the worst case is there a way to power cycle the device without actually unplugging it?
Maybe libfido2 isn't the best way to go about this process?

**Comment by nuno0529** [comment] 2021-04-14 05:39
@shawnkk
I think you can contact customer.support@authentrend.com for your case to have customized firmware with the behavior to disable the limitation of 3 retries only of 1 power cycle. Or maybe you can just use a usb hub with a switch button to on/off it.
Besides, to use libfido2 is still a good way in this case to communicate with ATKey. And thanks @martelletto, I think this issue can be closed here.

**Comment by martelletto** [comment] 2021-04-14 06:54
I suppose disabling `alwaysUv` with `fido2-token -Du <device>` would  also be an option in this case. Anyway, closing. Thank you!

**Closed by martelletto** 2021-04-14 06:54 UTC
