### ISSUE TITLE
Issue happen on using fido_dev_make_cred and return FIDO_ERR_INVALID_LENGTH

### ISSUE THREAD

**Issue by xuke100** [Yubico/libfido2#500] opened 2022-01-05 09:33 UTC
We are using libfido2 on mac laptop, and issue happen on using int fido_dev_make_cred(fido_dev_t* dev, fido_cred_t * cred, const char *) and return FIDO_ERR_INVALID_LENGTH,
does any experts can help to point out which invalid fido_cred_t or fido_dev_t may not correct?

what we set in cred:

**cd**: "type":"webauthn.create","challenge":"Yg7fiTPnO-70yc20oZ_ttMOtdov7tj7Ms0M56bgu-qw","origin":"https://webauthn.io". len-115
**cdh**: sha256(cd). len-32
**rp**: id-"webauthn.io",  name-"webauthn.io"
**user**: id-ptr, display_name-"test", name-"test", icon-""
**type**: -7

**Comment by kongeo** [comment] 2022-01-05 09:59
Hi, thanks for your question! Would you please enable debug logging in the library by setting the FIDO_DEBUG environment variable to 1 and share with us the output?

**Comment by xuke100** [comment] 2022-01-07 01:55
Thanks for help, we found that issue is can't set "" for icon in User if icon is NULL

**Comment by kongeo** [comment] 2022-01-07 07:53
Glad you've found the cause of the issue! Closing this as resolved :)

**Closed by kongeo** 2022-01-07 07:53 UTC
Labels: question
