### ISSUE TITLE
windows: abstraction layer for system's native API

### ISSUE THREAD

**Issue by Pettor** [Yubico/libfido2#34] opened 2019-05-07 09:03 UTC
I have a problem with the libfido2 detecting any attached key on my Surface Book 2. I have tried multiple keys and using webauth demos or the YubicoManager they all successfully detect the key, but the number of devices from the `fido_dev_info_manifest` call is always 0. Running the same code on other laptops/desktops works with the library detecting multiple keys (`fido_dev_info_manifest` returning > 0 devices). 

The drivers for the keys always installs correctly and Windows recognize the key as a security device etc. I have tried keys from Yubico and some keys from other vendors.

The Windows version I have installed is 1903 (release preview) but I have tried attaching the key using a Virtual Machine with Windows 7 and earlier Windows 10 versions and still the same problem.

```
fido_dev_t *device = NULL;
fido_dev_info_t *deviceInfoList;
size_t ndevs = 0;
fido_init(0);
if ((deviceInfoList = fido_dev_info_new(64)) && fido_dev_info_manifest(deviceInfoList, 64, &ndevs) == FIDO_OK)
```

This code will return `FIDO_OK` but with `ndevs` set to 0 with a key attached to the computer.

**Comment by Pettor** [comment] 2019-05-07 09:58
I checked how Windows device manager recognizes the device for me and it shows up as a `HID-compliant fido` device. Another device where the key is successfully found it shows up as a `USB input device`.

![bild](https://user-images.githubusercontent.com/54952/57291276-69f15980-70bf-11e9-9e30-41c9b62aeb88.png)

**Comment by martelletto** [comment] 2019-05-07 10:41
Could this be due to [1]? If the host OS restricts access to FIDO devices, then I suppose a guest OS won't be able to see it. YubiKey Manager does not use the FIDO interface directly, which is probably why it is able to talk to the key.

Alternatively, could you try to run the provided manifest example with FIDO_DEBUG=1?

[1] https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/webauthnapis

**Comment by Pettor** [comment] 2019-05-07 12:14
Ah that must be it. 1903 is the first version restricting the devices and that would explain why even VM can't access it, since it's on OS level. I tired several demos using WebAuth and they all work fine with a native Fido2 dialogue being shown.

Does it make sense to add support for these APIs in libfido2 or would that be a separate implementation for each third party dev to utilize if necessary?

**Comment by martelletto** [comment] 2019-05-07 14:01
The short answer is: we still don't know. :) Most likely the latter, as the former means two versions of libfido2 for Windows (one wrapped around the native API, another with direct HID access for compatibility with < 1903) which would land us straight onto #ifdef hell.

**Comment by martelletto** [comment] 2019-06-11 12:42
Hi @Pettor, a quick update on this:

I had a closer look at Microsoft's WebAuthn API, and it should be possible to wrap libfido2 around it. However, I probably won't have time to do the work in the near future. As it stands, use of libfido2 for communication with a FIDO2 authenticator on 1903 is still possible with Administrator privileges.

-p.

**Comment by borrrden** [comment] 2020-01-16 03:18
There is no API for looking for devices though?  Is all of that abstracted away?

**Comment by martelletto** [comment] 2020-01-16 15:04
Looks like it is all abstracted away: https://github.com/microsoft/webauthn/blob/master/webauthn.h#L59

Given there doesn’t seem to be a way to find devices, what I had in mind was for fido_hid_manifest() to always return at least a spoofed cross-platform authenticator (with indicative path/vendor/product strings) and depending on WebAuthNIsUserVerifyingPlatformAuthenticatorAvailable(), a platform authenticator.

-p.

**Comment by riedel** [comment] 2020-02-27 13:07
Sorry for commenting on this without adding too much to the solution, but IMHO the solution as bad as it sounds is to not fix it (unless a full CTAP passthru is provided by Microsoft).

It is Microsoft who have messed up the situation just because they want to use their market share to presure browser vendors to include their Windows Hello stuff without all the hassle of adjusting to the actual standard. The CTAP2 HID device is working well under elevation, so there cannot be a technical reasons (they know browser cannot will not run under elevated priviledges).

Integrating even a limited version will put the (minimal) pressure off Microsoft and people will have to live with the bits of the CTAP protocol Microsoft choses to expose.  Microsoft should go through the trouble and rather emulate CTAP and expose a virtual HID device for their stuff. 

My (last) hope is that e.g. git using ssh+fido2 will become a common use case and it will be too much hassle for them to force their own stuff.

**Comment by prusnak** [comment] 2020-04-10 09:49
As #153 was closed as duplicate of this I suggest to change the description of the issue to something more sane, such as "Windows: Abstraction layer for system's native API"

**Comment by martelletto** [comment] 2020-04-14 11:46
For anyone with the inclination (and time) to do the work, https://github.com/tavrez/openssh-sk-winhello would be a good starting point. There is no need to support the entirety of libfido2's API at once; we could begin by implementing the bits and pieces used by OpenSSH, which is effectively what openssh-sk-winhello does.

**Closed** 2021-06-16 07:21 UTC
Labels: feature request, help wanted
