### ISSUE TITLE
Is there a way to do U2F registration and assertion without user gesture action ?

### ISSUE THREAD

**Issue by sb230132** [Yubico/libfido2#262] opened 2021-01-12 07:28 UTC
Hi,
My requirement is automate user registration and assertion using U2F. Both steps require user to touch the device. Is there a way to automate the testing ?
I see in code that in u2f_register() the program (fido2-cred) waits for user to touch the device. Is there anything which i can change here to skip user gesture action and continue.

Here is the code:
	do {
		if (fido_tx(dev, CTAP_CMD_MSG, iso7816_ptr(apdu),
		    iso7816_len(apdu)) < 0) {
			fido_log_debug("%s: fido_tx", __func__);
			r = FIDO_ERR_TX;
			goto fail;
		}
		if ((reply_len = fido_rx(dev, CTAP_CMD_MSG, &reply,
		    sizeof(reply), ms)) < 2) {
			fido_log_debug("%s: fido_rx", __func__);
			r = FIDO_ERR_RX;
			goto fail;
		}
		if (usleep((unsigned)(ms == -1 ? 100 : ms) * 1000) < 0) {
			fido_log_debug("%s: usleep", __func__);
			r = FIDO_ERR_RX;
			goto fail;
		}
	} while (((reply[0] << 8) | reply[1]) == SW_CONDITIONS_NOT_SATISFIED);

fido_assert_set_up();
IN above API when user presence is set to OMIT or FALSE, fido2-assert program has no difference. What does user presence flag mean ?

Regards
Satish.B

**Comment by martelletto** [comment] 2021-01-12 07:59
U2F and FIDO2 authenticators require a test of user presence for registration. U2F 1.0 authenticators require a test of user presence for authentication, whereas U2F 1.2 authenticators _may_ not. However, U2F authentication without user presence is currently unsupported in libfido2 as the code stands. If you really need this feature, let me know and I will prepare a patch for you.

FIDO2 authenticators require a test of user presence for registration, but do not require a test of user presence for authentication. FIDO2 authentication without user presence is supported in libfido2.

That said, you specifically mentioned "testing" in your question. Is the goal to automate the actual user-flow involving a real authenticator, or is it to automate the testing of the functionality you're developing? If it is the latter, there are options we could explore.

-p.

**Comment by sb230132** [comment] 2021-01-12 08:29
To my knowledge user presence means user is expected to perform a gesture action. I hope its correct.
Assuming my understanding of user presence flag is correct, what I need is U2F authentication without user presence, so that during registration and assertion, gesture action can be skipped. This i need because i need my test scripts to run without any manual intervention.
 
Goal is to automate testing of functionality iam developing. However one of the functionality is to perform user authentication (U2F) process with a real authenticator. This is done and tested manually. Iam stuck with automating the complete user authentication flow with a real FIDO device.

I checked tools/test.sh this script will still prompt user to touch the device.

Thanks for your time and help.

**Comment by martelletto** [comment] 2021-01-12 09:11
Thank you for the clarification. Do the modifications implemented in https://github.com/Yubico/libfido2/compare/u2f-1.2-no-up help? Please note that you will only be able to perform authentications without user presence; registrations will still require it.

**Comment by sb230132** [comment] 2021-01-12 09:27
Thank you.
Is there any possibility of skipping user presence during registration process ?

**Comment by martelletto** [comment] 2021-01-12 10:03
Unfortunately, that's not an option, neither in U2F nor in FIDO2, by design.

**Comment by nuno0529** [comment] 2021-01-12 11:26
> ... what I need is U2F authentication without user presence ...
> Goal is to automate testing of functionality...

You should try the approach from u2f authenticator with open source firmware support.

**Comment by martelletto** [comment] 2021-01-15 16:10
Closing in the understanding that the questions have been answered. Thank you for your input, @nuno0529.

**Closed by martelletto** 2021-01-15 16:10 UTC
Labels: question
